# Generated by Django 2.2 on 2020-01-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_to_table', '0003_auto_20200119_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
