# Generated by Django 2.2 on 2020-01-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_to_table', '0005_auto_20200119_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
