# Generated by Django 2.2 on 2020-01-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_to_table', '0007_auto_20200119_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='people',
            index=models.Index(fields=['date'], name='csv_to_tabl_date_4ab4e2_idx'),
        ),
    ]
