# Generated by Django 2.2 on 2020-01-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_to_table', '0009_auto_20200120_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='course_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='currency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='people',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='people',
            index=models.Index(fields=['date'], name='csv_to_tabl_date_4ab4e2_idx'),
        ),
    ]
