# Generated by Django 2.2 on 2020-01-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_to_table', '0010_auto_20200121_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='callback_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='people',
            name='group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='people',
            name='obligation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='people',
            name='payment_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='people',
            name='payment_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='people',
            name='request_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='people',
            name='total_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='wishes',
            field=models.TextField(blank=True),
        ),
    ]
