# Generated by Django 2.2.4 on 2020-02-07 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_to_table', '0011_auto_20200121_2108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
    ]
