# Generated by Django 2.2.4 on 2020-02-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('university', models.CharField(blank=True, max_length=100)),
                ('work', models.CharField(blank=True, max_length=100)),
                ('where_from', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=100)),
                ('course_price', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('wishes', models.TextField(blank=True)),
                ('callback_time', models.DateTimeField(blank=True, null=True)),
                ('request_status', models.CharField(blank=True, max_length=100)),
                ('first_payment_date', models.DateTimeField(blank=True, null=True)),
                ('full_payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_history', models.TextField(blank=True)),
                ('total_payment', models.IntegerField(blank=True, null=True)),
                ('obligation', models.IntegerField(blank=True, null=True)),
                ('group', models.ManyToManyField(to='authorization.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('university', models.CharField(blank=True, max_length=100)),
                ('work', models.CharField(blank=True, max_length=100)),
                ('where_from', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=100)),
                ('course_price', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('wishes', models.TextField(blank=True)),
                ('callback_time', models.DateTimeField(blank=True, null=True)),
                ('request_status', models.CharField(blank=True, max_length=100)),
                ('payment_history', models.TextField(blank=True)),
                ('total_payment', models.IntegerField(blank=True, default=0)),
                ('payment_source', models.CharField(blank=True, max_length=100)),
                ('obligation', models.IntegerField(blank=True, null=True)),
                ('group', models.ManyToManyField(to='authorization.Group')),
            ],
        ),
    ]
