# Generated by Django 2.2.4 on 2020-01-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('work', models.CharField(max_length=100)),
                ('where_from', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('currency', models.TextField(max_length=100)),
                ('course_price', models.IntegerField()),
                ('request_status', models.CharField(max_length=100)),
                ('callback_time', models.DateTimeField()),
                ('payment_history', models.TextField()),
                ('total_payment', models.IntegerField()),
                ('payment_source', models.CharField(max_length=100)),
                ('obligation', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('wishes', models.TextField()),
            ],
        ),
    ]
