# Generated by Django 2.2.4 on 2020-02-07 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20200207_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily',
            name='group',
        ),
        migrations.AddField(
            model_name='daily',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authorization.Group'),
        ),
    ]
