# Generated by Django 2.2.4 on 2020-02-07 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20200207_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authorization.Group'),
        ),
        migrations.RemoveField(
            model_name='people',
            name='group',
        ),
        migrations.AddField(
            model_name='people',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authorization.Group'),
        ),
    ]
