# Generated by Django 2.2.4 on 2020-01-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20200114_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='callback_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
