# Generated by Django 2.2.4 on 2020-02-07 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_auto_20200207_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authorization.Course'),
        ),
    ]
