# Generated by Django 2.2.4 on 2020-01-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_auto_20200114_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
