# Generated by Django 2.2.4 on 2020-01-17 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_auto_20200116_0106'),
        ('authorization', '0005_auto_20200116_1705'),
    ]

    operations = [
    ]
