# Generated by Django 2.2.4 on 2020-01-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_merge_20200117_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='obligation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
