# Generated by Django 2.2.8 on 2020-02-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_group_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='course_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='daily',
            name='obligation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
