# Generated by Django 2.2.4 on 2020-01-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_auto_20200120_2048'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='daily',
            index=models.Index(fields=['request_date'], name='authorizati_request_d10f99_idx'),
        ),
    ]
