# Generated by Django 2.2.4 on 2020-01-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_auto_20200122_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('university', models.CharField(blank=True, max_length=100)),
                ('work', models.CharField(blank=True, max_length=100)),
                ('where_from', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=100)),
                ('course_price', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('wishes', models.TextField(blank=True)),
                ('callback_time', models.DateTimeField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('request_status', models.CharField(blank=True, max_length=100)),
                ('payment_history', models.TextField(blank=True)),
                ('total_payment', models.IntegerField(blank=True, null=True)),
                ('payment_source', models.CharField(blank=True, max_length=100)),
                ('obligation', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='groups',
            index=models.Index(fields=['request_date'], name='authorizati_request_fdee7b_idx'),
        ),
    ]
