# Generated by Django 2.2.4 on 2020-02-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_auto_20200214_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='ip',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='people',
            name='ip',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
