# Generated by Django 2.2.4 on 2020-01-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0010_auto_20200124_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('university', models.CharField(blank=True, max_length=100)),
                ('work', models.CharField(blank=True, max_length=100)),
                ('where_from', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=100)),
                ('course_price', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('wishes', models.TextField(blank=True)),
                ('callback_time', models.DateTimeField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('request_status', models.CharField(blank=True, max_length=100)),
                ('payment_history', models.TextField(blank=True)),
                ('total_payment', models.IntegerField(blank=True, null=True)),
                ('payment_source', models.CharField(blank=True, max_length=100)),
                ('obligation', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.RemoveIndex(
            model_name='group',
            name='authorizati_group_5a4748_idx',
        ),
        migrations.RemoveField(
            model_name='group',
            name='callback_time',
        ),
        migrations.RemoveField(
            model_name='group',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='group',
            name='country',
        ),
        migrations.RemoveField(
            model_name='group',
            name='course',
        ),
        migrations.RemoveField(
            model_name='group',
            name='course_price',
        ),
        migrations.RemoveField(
            model_name='group',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='group',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='group',
            name='email',
        ),
        migrations.RemoveField(
            model_name='group',
            name='group',
        ),
        migrations.RemoveField(
            model_name='group',
            name='obligation',
        ),
        migrations.RemoveField(
            model_name='group',
            name='payment_history',
        ),
        migrations.RemoveField(
            model_name='group',
            name='payment_source',
        ),
        migrations.RemoveField(
            model_name='group',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='group',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='group',
            name='request_status',
        ),
        migrations.RemoveField(
            model_name='group',
            name='total_payment',
        ),
        migrations.RemoveField(
            model_name='group',
            name='university',
        ),
        migrations.RemoveField(
            model_name='group',
            name='where_from',
        ),
        migrations.RemoveField(
            model_name='group',
            name='wishes',
        ),
        migrations.RemoveField(
            model_name='group',
            name='work',
        ),
        migrations.AddField(
            model_name='group',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='people',
            index=models.Index(fields=['group'], name='authorizati_group_5ca5ce_idx'),
        ),
    ]
