# Generated by Django 2.2.4 on 2020-02-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0012_auto_20200201_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='group',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
