# Generated by Django 2.2.4 on 2020-02-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0014_auto_20200201_2202'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='daily',
            name='authorizati_request_d10f99_idx',
        ),
        migrations.RemoveIndex(
            model_name='people',
            name='authorizati_group_5ca5ce_idx',
        ),
        migrations.RemoveField(
            model_name='people',
            name='group',
        ),
        migrations.AddField(
            model_name='people',
            name='group',
            field=models.ManyToManyField(to='authorization.Group'),
        ),
    ]
