# Generated by Django 2.2.4 on 2020-02-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0015_auto_20200205_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily',
            name='group',
        ),
        migrations.AddField(
            model_name='daily',
            name='group',
            field=models.ManyToManyField(to='authorization.Group'),
        ),
    ]
